### PR TITLE
Use 'EncounterEvaluationContext' in place of 'EvaluationContext'

### PR DESCRIPTION
**Pull request by kml27**
Allows for filtering patient summary results for a subset of encounters by adding parameter containing "encounterIds" with an EncounterIdSet() of encounter ids.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@kml27 did you get a chance to look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by kml27** [comment]
@jsibley What are your thoughts on @mseaton 's suggested alternative?

**Comment by jsibley** [comment]
O.k., thanks @mseaton, we'll try that out.

**Comment by mks-d** [comment]
@mseaton would you be ok to letting the evaluation context be overridden by introducing a new public method
```java
evaluatePatientSummaryTemplate(PatientSummaryTemplate patientSummaryTemplate,
  Integer patientId, Map<String, Object> parameters, EvaluationContext context)
```
?

**Pull request closed without merging**
